plugins { id 'com.android.application' }
android {
    namespace 'ru.tessavie.widgets'
    compileSdk 34
    defaultConfig {
        applicationId 'ru.tessavie.widgets'
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName '0.1.0-preview'
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }
    compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
    buildTypes {
        release { minifyEnabled false }
        preview {
            initWith release
            debuggable false
            signingConfig signingConfigs.debug
        }
    }
}
dependencies {
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.json:json:20240303'
    androidTestImplementation 'androidx.test:runner:1.5.2'
    androidTestImplementation 'androidx.test:core:1.5.0'
    androidTestImplementation 'junit:junit:4.13.2'
}
