"""Remove only reviewed generated footers from an existing forum import.

Run on the production host. Default is a read-only business-data preview; --apply
backs up SQLite on the same host and PATCHes descriptions with revision checks.
Original import receipts are immutable. No customer text is embedded in this tool.
"""
import argparse
import datetime as dt
import hashlib
import importlib.util
import json
import os
from pathlib import Path
import sqlite3

ROOT = Path(__file__).resolve().parent
SPEC = importlib.util.spec_from_file_location('workbook_import', ROOT / 'import-task-workbook-plan.py')
helper = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(helper)
require = helper.require
WORKSPACE = '350cf609e61f3e35b9f89fc1556969d5'
BOARD = 'a48e176276e5109845e624b49776ad6e'
BATCH = 'forum_navigator_20260914'
RELEASE = '/opt/business-control/releases/20260915-team-accounting-fbeba08'
DB = '/var/lib/business-control/business-control.db'
STATE = Path('/var/lib/business-control/import-receipts/forum-description-cleanup-20260915.json')


def sha(text):
    return hashlib.sha256(text.encode()).hexdigest()


def cleaned_description(current, original, marker):
    separator = '\n\nИсходный блок:'
    require(original.count(separator) == 1 and original.endswith(marker), 'Unexpected original footer')
    footer = original[original.index(separator):]
    require(current.count(footer) == 1, 'Generated footer was changed or is absent; inspect before editing')
    require(current.count(marker) == 1, 'Ambiguous source marker')
    # Match exact generated bytes, not an open-ended regex; keep later user notes.
    result = current.replace(footer, '', 1)
    require(result.strip(), 'Refusing an empty task description')
    return result


def save(path, value):
    temp = path.with_suffix('.tmp')
    with os.fdopen(os.open(temp, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600), 'w', encoding='utf-8') as out:
        json.dump(value, out, ensure_ascii=False, indent=2)
        out.write('\n')
    temp.replace(path)


def snapshot(db):
    db.row_factory = sqlite3.Row
    records = {r['id']: dict(r) for r in db.execute('SELECT * FROM records WHERE workspace_id=?', (WORKSPACE,))}
    fields = [dict(r) for r in db.execute('SELECT f.* FROM record_field_values f JOIN records r ON r.id=f.record_id WHERE r.workspace_id=? ORDER BY f.record_id,f.field_id', (WORKSPACE,))]
    links = [dict(r) for r in db.execute('SELECT l.* FROM record_links l WHERE l.source_id IN (SELECT id FROM records WHERE workspace_id=?) OR l.target_id IN (SELECT id FROM records WHERE workspace_id=?) ORDER BY l.id', (WORKSPACE, WORKSPACE))]
    return {'records': records, 'fields': fields, 'links': links}


def verify_unchanged(before, after, changes):
    require(before['fields'] == after['fields'], 'Custom fields changed during cleanup')
    require(before['links'] == after['links'], 'Dependencies changed during cleanup')
    require(set(before['records']) == set(after['records']), 'Record membership changed during cleanup')
    for rid, old in before['records'].items():
        new = after['records'][rid]
        allowed = {'description', 'updated_at'} if rid in changes else set()
        require({k:v for k,v in old.items() if k not in allowed} == {k:v for k,v in new.items() if k not in allowed}, 'Other record properties changed: ' + rid)
        if rid in changes:
            require(new['description'] == changes[rid], 'Description verification failed: ' + rid)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--plan', required=True)
    parser.add_argument('--plan-sha256', required=True)
    parser.add_argument('--apply', action='store_true')
    args = parser.parse_args()
    raw = Path(args.plan).read_bytes()
    require(hashlib.sha256(raw).hexdigest() == args.plan_sha256, 'Plan hash differs')
    plan = json.loads(raw)
    require(plan['batchKey'] == BATCH and plan['workspace'] == {'id': WORKSPACE, 'name': 'Владов стартап'} and plan['board']['id'] == BOARD, 'Unexpected import scope')
    require(plan['operator'] == {'id': 1, 'username': 'artkozk'}, 'Unexpected operator')
    require(str(Path('/opt/business-control/current').resolve()) == RELEASE, 'Runtime changed; review first')
    original_receipt = Path('/var/lib/business-control/import-receipts/' + BATCH + '.json')
    receipt_bytes = original_receipt.read_bytes()
    receipt = json.loads(receipt_bytes)
    require(receipt['verified'] and receipt['planSha256'] == args.plan_sha256 and receipt['workspaceId'] == WORKSPACE and receipt['boardId'] == BOARD, 'Original receipt differs')
    task_rows = [row for row in plan['records'] if row['payload']['type'] == 'task']
    require(len(task_rows) == 81, 'Unexpected source task count')
    allowed_ids = {receipt['recordIds'][row['key']] for row in task_rows}
    require(len(allowed_ids) == 81, 'Duplicate task mapping')
    import fcntl
    with open('/run/business-control-import-plan.lock', 'w') as lock, sqlite3.connect(DB, timeout=20) as db:
        fcntl.flock(lock, fcntl.LOCK_EX | fcntl.LOCK_NB)
        state = json.loads(STATE.read_text()) if STATE.exists() else {'planSha256': args.plan_sha256, 'records': {}, 'verified': False}
        require(state['planSha256'] == args.plan_sha256, 'Cleanup receipt belongs to another plan')
        before = snapshot(db)
        planned = []
        with helper.sessions(db, [plan['operator']], WORKSPACE) as tokens:
            api = helper.API(WORKSPACE, tokens)
            def call(path, method='GET', body=None):
                require(path == '/records?includeArchived=true' and method == 'GET' or
                        path.startswith('/records/') and path[len('/records/'):] in allowed_ids and method in ('GET', 'PATCH'), 'Out-of-scope API call')
                if method == 'PATCH':
                    require(args.apply and set(body) == {'description', 'expectedUpdatedAt', 'reason'}, 'Unexpected mutation')
                return api(path, method, body, actor=1)
            rows = call('/records?includeArchived=true')
            by_id = {r['id']: r for r in rows}
            for source in task_rows:
                rid = receipt['recordIds'][source['key']]
                record = by_id.get(rid)
                require(record and record['workspaceId'] == WORKSPACE and record['collectionId'] == BOARD and record['type'] == 'task', 'Task moved or unavailable: ' + source['key'])
                old = record.get('description', '')
                mark = helper.marker(plan, source['key'])
                prior = state['records'].get(rid)
                if prior and sha(old) == prior['afterSHA256']:
                    continue
                result = cleaned_description(old, source['payload']['description'], mark)
                planned.append((record, result))
            # Validate every task before the first write. Changed source footers stop
            # the whole attempt; stale live revisions stop at their PATCH safely.
            if args.apply and planned:
                backup = Path('/var/lib/business-control/backups') / ('pre-forum-description-cleanup-' + dt.datetime.now(dt.timezone.utc).strftime('%Y%m%dT%H%M%SZ'))
                backup.mkdir(mode=0o700)
                target = backup / 'business-control.db'
                with sqlite3.connect(target) as copy:
                    db.backup(copy)
                    require(copy.execute('PRAGMA integrity_check').fetchone()[0] == 'ok', 'Backup integrity failure')
                target.chmod(0o600)
                state.setdefault('backups', []).append(str(target))
                save(STATE, state)
                for record, result in planned:
                    rid = record['id']
                    # Persist intended hashes first so a lost response is reconciled
                    # without rewriting a task or restoring the old footer.
                    state['records'][rid] = {'beforeSHA256': sha(record['description']), 'afterSHA256': sha(result), 'confirmed': False}
                    save(STATE, state)
                    call('/records/' + rid, 'PATCH', {'description': result, 'expectedUpdatedAt': record['updatedAt'], 'reason': 'Убраны служебные пояснения переноса из Excel по просьбе команды'})
                    fresh = call('/records/' + rid)['record']
                    require(fresh['description'] == result, 'Saved text differs')
                    state['records'][rid]['confirmed'] = True
                    save(STATE, state)
            changes = {record['id']: result for record, result in planned} if args.apply else {}
            verify_unchanged(before, snapshot(db), changes)
            require(original_receipt.read_bytes() == receipt_bytes, 'Original import receipt changed')
            if args.apply:
                for rid, proof in state['records'].items():
                    require(rid in allowed_ids and sha(by_id[rid]['description'] if rid not in changes else changes[rid]) == proof['afterSHA256'], 'Receipt verification differs')
                    proof['confirmed'] = True
                state.update(verified=True, verifiedAt=helper.stamp(dt.datetime.now(dt.timezone.utc)), workspaceId=WORKSPACE, boardId=BOARD)
                save(STATE, state)
        print(json.dumps({'apply': args.apply, 'eligibleTasks': len(task_rows), 'changedThisRun': len(planned) if args.apply else 0, 'plannedChanges': len(planned), 'alreadyClean': len(task_rows)-len(planned), 'protectedPropertiesUnchanged': True, 'customFieldsUnchanged': True, 'linksUnchanged': True, 'originalReceiptUnchanged': True, 'temporarySessionRemoved': True, 'backup': state.get('backups', [])[-1:] , 'cleanupReceipt': str(STATE) if args.apply else None}, ensure_ascii=False))


if __name__ == '__main__':
    main()
