const test=require('node:test'), assert=require('node:assert/strict');
const fs=require('node:fs');
const modulePromise=import('data:text/javascript;base64,'+fs.readFileSync(__dirname+'/field-conversion.js').toString('base64'));
test('compatible choices never offer an arbitrary lossy type',async()=>{const m=await modulePromise;assert.deepEqual(m.fieldConversionChoices('select'),['select','multi_select']);assert.deepEqual(m.fieldConversionChoices('date'),['date']);assert.deepEqual(m.fieldConversionChoices('number'),['number','money']);});
test('preview keeps empty, missing and measured zero distinct',async()=>{const m=await modulePromise;for(const [value,want] of [[null,'Не задано'],['','Пусто'],[[],'Пусто'],[0,'0'],[false,'Нет']])assert.equal(m.fieldConversionValue(value,{fieldType:'number'}),want);});
test('choice IDs are rendered as labels for both scalar and array values',async()=>{const m=await modulePromise,field={fieldType:'select',options:[{id:'a',name:'Почта'},{id:'b',name:'Чат'}]};assert.equal(m.fieldConversionValue('a',field),'Почта');assert.equal(m.fieldConversionValue(['a','b'],field),'Почта, Чат');});
test('preview escapes record titles, option labels and multiline values',async()=>{const m=await modulePromise;const html=m.fieldConversionPreviewHTML({from:'text',to:'long_text',affected:1,changed:0,examples:[{recordTitle:'<img onerror=x>',value:'<script>x</script>',converted:'A & B'}],defaultBefore:'"x"',defaultAfter:'"x"'},{fieldType:'text'});assert.ok(!html.includes('<img'));assert.ok(!html.includes('<script>'));assert.ok(html.includes('&lt;script&gt;'));assert.ok(html.includes('A &amp; B'));assert.ok(html.includes('&quot;x&quot;'));});
test('preview explains hidden affected records and includes default even with no examples',async()=>{const m=await modulePromise;const html=m.fieldConversionPreviewHTML({from:'number',to:'money',affected:0,changed:0,examples:[],archived:2,detached:3,defaultBefore:0,defaultAfter:0},{fieldType:'number'});assert.ok(html.includes('архивных: 2'));assert.ok(html.includes('значение: 3'));assert.ok(html.includes('0 → 0'));assert.ok(html.includes('Заполненных карточек пока нет'));});
test('numeric preview uses exact stored decimal text',async()=>{const m=await modulePromise,raw='9007199254740993.125';const html=m.fieldConversionPreviewHTML({from:'number',to:'money',affected:1,changed:0,examples:[{value:9007199254740992,converted:9007199254740992,valueRaw:raw,convertedRaw:raw}],defaultBeforeRaw:raw,defaultAfterRaw:raw},{fieldType:'number'});assert.equal(html.split(raw).length-1,4);assert.ok(!html.includes('9007199254740992'));});
