const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const c=vm.createContext({});for(const file of ['page-form-elements.js','page-element-styles.js'])vm.runInContext(fs.readFileSync(require('node:path').join(__dirname,file),'utf8').replaceAll('\r\n','\n').replace(/^import .*;\n/gm,'').replaceAll('export ',''),c);
const run=s=>vm.runInContext(s,c);
test('legacy form appearance moves once without overwriting explicit nested properties or values',()=>{
 c.b={formFields:[{key:'custom:amount',width:6,label:'Amount',fontSize:24,color:'#123456',background:'#abcdef'}],elementStyles:{'formControl:custom:amount':{padding:0,fontSize:18}}};run('migrateFormElementStyles(b)');assert.equal(c.b.formFields[0].width,6);assert.equal(c.b.formFields[0].fontSize,undefined);assert.equal(c.b.elementStyles['formLabel:custom:amount'].fontSize,24);assert.equal(c.b.elementStyles['formControl:custom:amount'].fontSize,18);assert.equal(c.b.elementStyles['formControl:custom:amount'].padding,0);const before=JSON.stringify(c.b);run('migrateFormElementStyles(b)');assert.equal(JSON.stringify(c.b),before);delete c.b.elementStyles['formControl:custom:amount'];run('migrateFormElementStyles(b)');assert.equal(c.b.elementStyles['formControl:custom:amount'],undefined);
});
test('form editor names nested controls and keeps required-input removal in form structure',()=>{
 c.b={kind:'form',formFields:[{key:'title'},{key:'custom:amount',label:'Own <amount>'}]};c.e=s=>String(s).replaceAll('<','&lt;').replaceAll('>','&gt;');const html=run("elementStyleConfig(b,null,'formControl:custom:amount',e)");assert.match(html,/Own &lt;amount&gt;/);assert.match(html,/Убрать поле можно в структуре формы/);assert.ok(!html.includes('data-element-property="hidden"'));assert.match(run("elementStyleConfig(b,null,'formLabel:title',e)"),/data-element-property="hidden"/);
});
