const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const c=vm.createContext({});for(const file of ['page-calculations.js','page-record-bindings.js','page-record-card.js','page-element-styles.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,file),'utf8').replace(/^import .*;\r?\n/gm,'').replaceAll('export ',''),c);
const run=s=>vm.runInContext(s,c);c.e=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');c.display=(f,v)=>v===null||v===undefined?'':f.fieldType==='checkbox'?(v?'Да':'Нет'):String(v);
function setup(){c.collection={fields:[{id:'n',name:'Number',fieldType:'number'},{id:'b',name:'Check',fieldType:'checkbox'}]};c.record={title:'Original',customFields:{n:0,b:false}};c.block={fields:['n','b'],recordCard:{enabled:true,columns:2,gap:0,parts:[{id:'note',kind:'text',text:'<hello>',width:12},{id:'value',kind:'field',fieldId:'n',label:'Own name',width:6},{id:'title',kind:'title',width:6},{id:'check',kind:'field',fieldId:'b',width:12,hideLabel:true}]}};}
test('one card definition repeats over different records without copying values',()=>{setup();const before=JSON.stringify(c.block);let html=run('recordCardBody(block,record,collection,display,e)');assert.ok(html.indexOf('&lt;hello&gt;')<html.indexOf('Own name'));assert.ok(html.indexOf('Own name')<html.indexOf('Original'));assert.match(html,/>0<\/span>/);assert.match(html,/>Нет<\/span>/);assert.ok(!html.includes('>Check<'));assert.ok(!html.includes('<hello>'));c.record={title:'Second',customFields:{n:42,b:true}};html=run('recordCardBody(block,record,collection,display,e)');assert.match(html,/>42<\/span>/);assert.match(html,/>Да<\/span>/);assert.equal(JSON.stringify(c.block),before);});
test('hidden parts keep sources, empty cards retain an opening hint and unavailable fields are explicit',()=>{setup();for(const p of c.block.recordCard.parts)p.hidden=true;assert.match(run('recordCardBody(block,record,collection,display,e)'),/Открыть запись/);assert.equal(c.record.customFields.n,0);c.block.recordCard.parts[1].hidden=false;c.collection.fields=[];assert.match(run('recordCardBody(block,record,collection,display,e)'),/Поле недоступно/);});
test('switching to standard layout preserves custom parts and returning restores them',()=>{setup();const before=JSON.stringify(c.block.recordCard.parts);c.block.recordCard.enabled=false;let html=run('recordCardBody(block,record,collection,display,e)');assert.match(html,/app-record-values/);assert.ok(!html.includes('Own name'));c.block.recordCard.enabled=true;assert.match(run('recordCardBody(block,record,collection,display,e)'),/Own name/);assert.equal(JSON.stringify(c.block.recordCard.parts),before);});
test('all configured field values participate in search and formula slots retain each record context',()=>{setup();c.block.recordBindings={subtitle:{fieldId:'n',calculation:[{operation:'add',value:7}],suffix:' units'}};c.block.recordCard.parts.push({id:'formula',kind:'subtitle',width:12});assert.match(run('recordCardBody(block,record,collection,display,e)'),/7 units/);assert.match(run('recordCardSearchText(block,record,collection,display)'),/0\s+Нет/);});
test('card layout and style targets preserve explicit zero and user labels safely',()=>{setup();const vars={};c.host={style:{setProperty:(k,v)=>vars[k]=v}};run('applyRecordCardLayout(host,block)');assert.equal(c.host.className,'app-record-grid app-record-grid-2');assert.equal(vars['--record-card-gap'],'0px');const targets=run('elementStyleTargets(block,collection)');c.block.kind='records';assert.ok(run('elementStyleTargets(block,collection)').some(t=>t.key==='recordPart:value'&&t.label.includes('Own name')));assert.match(run('recordCardConfig(block,collection,e)'),/&lt;hello&gt;/);});

test("initial custom card preserves all forty selected fields",()=>{c.block={fields:Array.from({length:40},(_,i)=>"f"+i)};let id=0;c.next=()=>"p"+(++id);const card=run("defaultRecordCard(block,next)");assert.equal(card.parts.length,42);assert.equal(new Set(card.parts.map(p=>p.id)).size,42);});
